In [1]:
import torch

ModuleNotFoundError: No module named 'torch'

In [2]:
conda install pytorch cpuonly -c pytorch -y


Note: you may need to restart the kernel to use updated packages.


Traceback (most recent call last):
  File "C:\Users\mrina\Anaconda3\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'


In [1]:
import torch

In [4]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

In [6]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [7]:
t1.shape


torch.Size([])

In [8]:
t2.shape

torch.Size([4])

In [12]:
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5., requires_grad=True)

In [14]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [15]:
y.backward()

In [16]:
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [2]:
import numpy as np
x=np.array([[1,2], [3,4.]])

In [3]:
x

array([[1., 2.],
       [3., 4.]])

In [4]:
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [5]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [6]:
x=y.numpy()
x

array([[1., 2.],
       [3., 4.]])